Use mb_health instead of curl for HEALTHCHECK

diff --git a/docker/Dockerfile.dev b/docker/Dockerfile.dev
--- a/docker/Dockerfile.dev
+++ b/docker/Dockerfile.dev
@@ -158,9 +158,7 @@ COPY --from=builder \
   /matterbridge-eve-weather/*.tgz \
   ./
 
-RUN apt-get update && \
-  apt-get install -y --no-install-recommends curl && \
-  apt-get clean && \
+RUN \
   npm install --no-fund --no-audit --omit=dev --global *.tgz && \
   npm uninstall -g corepack && \
   npm cache clean --force && \
@@ -180,7 +178,8 @@ RUN apt-get update && \
 
 # Add Docker HEALTHCHECK
 HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=5 \
-  CMD curl --fail http://localhost:8283/health || exit 1
+  #  CMD curl --fail http://localhost:8283/health || exit 1
+  CMD mb_health
 
 # Copy and execute the entrypoint script
 COPY ./docker/entrypoint.dev.sh ./
diff --git a/docker/Dockerfile.latest b/docker/Dockerfile.latest
--- a/docker/Dockerfile.latest
+++ b/docker/Dockerfile.latest
@@ -22,9 +22,10 @@ LABEL org.opencontainers.image.title="matterbridge" \
 
 WORKDIR /matterbridge
 COPY ./.dockerbuild.json ./
-RUN apt-get update && \
-  apt-get install -y --no-install-recommends curl && \
-  apt-get clean && \
+RUN \
+  #  apt-get update && \
+  #  apt-get install -y --no-install-recommends curl && \
+  #  apt-get clean && \
   npm install --global --no-fund --no-audit --omit=dev \
   matterbridge \
   matterbridge-zigbee2mqtt \
@@ -57,7 +58,8 @@ RUN apt-get update && \
 
 # Add Docker HEALTHCHECK
 HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=5 \
-  CMD curl --fail http://localhost:8283/health || exit 1
+  #  CMD curl --fail http://localhost:8283/health || exit 1
+  CMD mb_health
 
 # Copy and execute the entrypoint script
 COPY ./docker/entrypoint.latest.sh ./
